service: ika-notification

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1
  profile: misato

# package:
  # exclude:
    # - node_modules/aws-sdk/**

functions:
  notification:
    handler: dist/handler.handler
    memorySize: 138
    events:
      - http:
          path: '/'
          method: get
